# Generated by Django 6.1 on 2026-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت شده'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده'), ('RETURN_REQUESTED', 'درخواست مرجوعی'), ('RETURNED', 'مرجوع شده'), ('REFUNDED', 'مبلغ مسترد شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
