# Generated by Django 6.1 on 2026-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ اولیه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت در زمان ثبت'),
        ),
    ]
