# Generated by Django 5.0.14 on 2026-08-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('promotions', '0002_cartrule_promotion_minimum_cart_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion'),
        ),
    ]
