# Generated by Django 5.0.14 on 2026-08-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Discount code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (e.g. 10.00 for 10%)', max_digits=5, null=True)),
                ('discount_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount discount', max_digits=10, null=True)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
