# Generated by Django 5.0.14 on 2026-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Free shipping on orders over $500', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_cart_total', models.DecimalField(decimal_places=2, help_text='Minimum cart total to trigger this rule', max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount on entire cart', max_digits=5, null=True)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='minimum_cart_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required to use this coupon', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used overall', null=True),
        ),
    ]
