# Generated by Django 5.0.14 on 2026-08-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_cartrule_promotion_minimum_cart_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrule',
            options={'verbose_name': 'قانون سبد خرید', 'verbose_name_plural': 'قوانین سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد تخفیف روی کل سبد خرید', max_digits=5, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='is_free_shipping',
            field=models.BooleanField(default=False, verbose_name='ارسال رایگان'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='min_cart_total',
            field=models.DecimalField(decimal_places=2, help_text='حداقل مبلغ سبد خرید برای اعمال این قانون', max_digits=10, verbose_name='حداقل سبد خرید'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='name',
            field=models.CharField(help_text='مثلا: ارسال رایگان برای خریدهای بالای ۵ میلیون', max_length=255, verbose_name='نام قانون'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active_from',
            field=models.DateTimeField(verbose_name='فعال از تاریخ'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='فعال تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(help_text='کد تخفیف', max_length=50, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ ثابت تخفیف', max_digits=10, null=True, verbose_name='مبلغ ثابت تخفیف'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='درصد (مثلا 10.00 برای ۱۰٪)', max_digits=5, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='minimum_cart_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='حداقل مبلغ سبد خرید برای استفاده از این کد', max_digits=10, null=True, verbose_name='حداقل سبد خرید'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='times_used',
            field=models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده شده'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر دفعات مجاز استفاده از این کد', null=True, verbose_name='محدودیت استفاده'),
        ),
    ]
