# Generated by Django 5.0.14 on 2026-08-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_cartrule_options_alter_promotion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='🔥 کالکشن جدید', max_length=100, verbose_name='تگ بالای عنوان')),
                ('title_main', models.CharField(default='تکنولوژی را زندگی کن', max_length=255, verbose_name='عنوان اصلی')),
                ('title_highlight', models.CharField(blank=True, default='به سبک خودت', max_length=100, verbose_name='بخش رنگی عنوان (گرادیانت)')),
                ('description', models.TextField(verbose_name='متن توضیحات')),
                ('button_text', models.CharField(default='خرید را شروع کنید', max_length=50, verbose_name='متن دکمه اصلی')),
                ('button_link', models.CharField(default='#products', max_length=255, verbose_name='لینک دکمه اصلی (مثلا /search/)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش در سایت)')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنرهای صفحه اصلی',
            },
        ),
    ]
