# Generated by Django 6.1 on 2026-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrule',
            name='min_cart_total',
            field=models.DecimalField(decimal_places=0, help_text='حداقل مبلغ سبد خرید برای اعمال این قانون', max_digits=10, verbose_name='حداقل سبد خرید'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_fixed',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='مبلغ ثابت تخفیف', max_digits=10, null=True, verbose_name='مبلغ ثابت تخفیف'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='minimum_cart_value',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='حداقل مبلغ سبد خرید برای استفاده از این کد', max_digits=10, null=True, verbose_name='حداقل سبد خرید'),
        ),
    ]
