# Generated by Django 6.1 on 2026-08-22 12:50

import apps.promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_cartrule_min_cart_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[apps.promotions.models.validate_banner_size], verbose_name='تصویر بنر'),
        ),
    ]
