# Generated by Django 6.1 on 2026-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('COMPLETED', 'موفق'), ('FAILED', 'ناموفق'), ('REFUNDED', 'مسترد شده')], default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
    ]
