# Generated by Django 6.1 on 2026-08-21 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='نام شهر نامعتبر است.')], verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='ایران', max_length=100, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='نام استان نامعتبر است.')], verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10, message='آدرس پستی بسیار کوتاه است. لطفاً خیابان، کوچه و پلاک را کامل وارد کنید.')], verbose_name='خیابان و پلاک'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='نام باید حداقل ۲ حرف باشد')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='نام خانوادگی باید حداقل ۲ حرف باشد')], verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و ۱۱ رقم باشد. (مثال: 09123456789)', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
