# Generated by Django 5.0.14 on 2026-08-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_options_alter_category_options_and_more'),
        ('inventory', '0002_stockreservation_order'),
        ('orders', '0003_order_discount_amount_order_promotion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'موجودی انبار', 'verbose_name_plural': 'موجودی\u200cهای انبار'},
        ),
        migrations.AlterModelOptions(
            name='stockreservation',
            options={'verbose_name': 'رزرو موقت موجودی', 'verbose_name_plural': 'رزروهای موقت موجودی'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجودی قطعی'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.variant', verbose_name='محصول (متغیر)'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='تاریخ انقضای رزرو'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد رزرو شده'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه نشست (Session)'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.variant', verbose_name='محصول (متغیر)'),
        ),
    ]
