# Generated by Django 5.0.14 on 2026-08-18 07:33

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_variant_compare_at_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.catalog.models.validate_image_size]),
        ),
    ]
