# Generated by Django 5.0.14 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_review_dislikes_review_likes_review_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(blank=True, null=True, verbose_name='پیشنهاد خرید'),
        ),
    ]
