# Generated by Django 6.1 on 2026-08-22 06:45

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_review_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مشروح'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', validators=[apps.catalog.models.validate_image_size], verbose_name='تصویر'),
        ),
    ]
