# Generated by Django 6.1 on 2026-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت قبل از تخفیف', max_digits=10, null=True, verbose_name='قیمت خط خورده'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
    ]
