# Generated by Django 6.1 on 2026-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_variant_compare_at_price_alter_variant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_cache_timeout', models.IntegerField(default=15, help_text='مدت زمان کش شدن صفحه اصلی به دقیقه', verbose_name='زمان کش صفحه اصلی (دقیقه)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
